In [13]:
import gensim 

korea_docu = []
with open("korea.txt", encoding='utf-8') as file:
    for j, line in enumerate(file):
        korea_docu.append(gensim.utils.simple_preprocess(line))

korea_model = gensim.models.Word2Vec (korea_docu, size=5, window=5, min_count=1, workers=4)
korea_model.train(korea_docu, total_examples=len(korea_docu), epochs=1000)

(5314423, 8553000)

In [14]:
wordlist = []
count = []
for word, obj in korea_model.wv.vocab.items():
    wordlist.append(word)
    count.append(obj.count)
for _ in range(100):
    idx = count.index(max(count))
    print(wordlist[idx], max(count))
    del count[idx]
    del wordlist[idx]

the 944
of 555
shall 332
and 326
to 226
be 226
by 180
or 135
national 133
in 121
act 115
assembly 98
state 91
president 83
as 67
for 66
may 66
under 62
members 59
constitution 49
prescribed 47
not 47
court 45
citizens 42
public 41
have 41
all 40
is 38
on 37
other 37
with 36
council 35
conditions 34
office 33
determined 32
executive 31
matters 30
from 29
it 29
case 29
an 27
this 27
no 25
their 23
necessary 23
right 23
that 23
political 22
when 21
prime 21
minister 21
supreme 21
any 20
such 20
military 19
within 19
law 18
provided 18
at 18
appointed 18
time 17
person 17
are 17
more 17
pertaining 17
rights 16
its 16
organization 16
constitutional 16
except 16
who 16
justices 16
election 16
than 15
term 15
total 15
economic 14
basic 14
duty 14
officials 14
without 14
he 14
martial 14
important 14
they 14
member 14
affairs 14
republic 13
korea 13
security 13
request 13
his 13
judges 13
days 13
justice 12
order 12
freedom 12
treaties 12
laws 12
nor 12


In [16]:
import numpy as np

v1 = korea_model.wv['citizens']
dotlist = []
wordlist = []
for word, obj in korea_model.wv.vocab.items():
    wordlist.append(word)
    w = korea_model.wv[word]
    dotlist.append(abs(np.dot(v1, w) / np.linalg.norm(v1) / np.linalg.norm(w)))

for _ in range(100):
    idx = dotlist.index(min(dotlist))
    print(wordlist[idx], min(dotlist))
    del dotlist[idx]
    del wordlist[idx]

judiciary 0.0017672761
accredit 0.0020427613
otherwise 0.002403285
distribution 0.0024991482
disqualified 0.0032715548
treason 0.0038602531
five 0.0053571514
food 0.005790749
audit 0.0072713937
there 0.007428199
envoys 0.008054554
run 0.009743824
written 0.010048455
held 0.010415805
investigation 0.01140741
commutation 0.012313361
further 0.013109832
responsible 0.013132484
insurrection 0.014112067
growth 0.015217415
executed 0.015666865
matter 0.015698366
views 0.015884113
unification 0.016118554
apprehended 0.01662551
march 0.016943045
defending 0.019107528
less 0.019280657
incumbent 0.019574208
foreign 0.020242644
performance 0.020393444
stationing 0.02183948
controlled 0.022375287
event 0.022896968
rules 0.023170486
servicemen 0.024241816
proper 0.024436994
land 0.024573429
himself 0.024617542
observing 0.024718013
charged 0.02535497
adjudicated 0.02670472
states 0.02694929
improving 0.027373027
autonomy 0.027571753
become 0.027792761
educational 0.02830546
successors 0.028590461
s

In [36]:
v = ['citizens', 'distribution']

A = np.array([korea_model.wv[v[i]] for i in range(len(v))])
A = A.T
P = np.dot(A,np.dot(np.linalg.inv(np.dot(A.T, A)), A.T))

dotlist = []
wordlist = []
for word, obj in korea_model.wv.vocab.items():
    wordlist.append(word)
    w = korea_model.wv[word] / np.linalg.norm(w)
    
    dotlist.append(abs(np.linalg.norm(np.dot(P, w))))

for _ in range(100):
    idx = dotlist.index(min(dotlist))
    print(wordlist[idx], min(dotlist))
    del dotlist[idx]
    del wordlist[idx]

[[ 0.02025628  0.01357092 -0.00869751 -0.13637389 -0.03143732]
 [ 0.01357092  0.07866107  0.24746932 -0.10509966 -0.00152817]
 [-0.00869751  0.24746932  0.9259693   0.00854927  0.08461897]
 [-0.13637389 -0.10509965  0.00854927  0.92083865  0.20779312]
 [-0.03143732 -0.00152817  0.08461897  0.20779313  0.05427474]]
this 1.0289926e-07
death 1.4024388e-07
statement 1.4168043e-07
claim 1.6122404e-07
proceedings 1.7194056e-07
military 1.7354071e-07
pronounced 1.7967717e-07
qualified 1.8576938e-07
indicted 1.901833e-07
bodily 1.9231224e-07
entitled 1.9736197e-07
ground 1.9819164e-07
crimes 2.102653e-07
official 2.1441232e-07
innocent 2.3575804e-07
corresponding 2.4041358e-07
martial 2.458759e-07
reasons 2.548482e-07
compensations 2.7831254e-07
absence 2.8281355e-07
sentry 3.2313892e-07
damages 3.3518631e-07
proclamation 3.6160142e-07
conformity 3.7191333e-07
immune 3.737739e-07
aid 4.339253e-07
speedy 4.5010557e-07
combat 4.5169963e-07
officially 4.5998556e-07
judgment 4.6294466e-07
food 4.7