# Introduction to Python

## Basic commands

In [4]:
1 - 2

-1

In [5]:
4 * 5

20

In [6]:
7 / 5

1.4

In [8]:
3 ** 2

9

## Data types

In [9]:
type(10)

int

In [10]:
type(2.718)

float

In [11]:
type("hello")

str

## Variables

In [12]:
x = 10
print(x)

10


In [13]:
y = 3.14
x * y

31.400000000000002

## List

In [14]:
a = [1, 2, 3, 4, 5]
print(a)

[1, 2, 3, 4, 5]


In [15]:
len(a)

5

In [16]:
a[0]

1

In [17]:
a[4] = 99
print(a)

[1, 2, 3, 4, 99]


## Dictionary

In [18]:
me = {'height':180}
me['height']

180

In [20]:
me['weight'] = 70
print(me)

{'height': 180, 'weight': 70}


## Bool

In [22]:
hungry = True
sleepy = False
type(hungry)

bool

In [23]:
not hungry

False

In [24]:
hungry or sleepy

True

## if/else

In [25]:
hungry = True
if hungry:
    print("I'm hungry")

I'm hungry


In [26]:
hungry = False
if hungry:
    print("I'm hungry")
else:
    print("I'm not hungry")
    print("I'm sleepy")

I'm not hungry
I'm sleepy


## for

In [27]:
for i in [1, 2, 3]:
    print(i)

1
2
3


## Function

In [28]:
def hello():
    print("Hello world!")

In [29]:
hello()

Hello world!


In [30]:
def hello(object):
    print("Hello " + object + "!")

In [31]:
hello("cat")

Hello cat!


## Class

In [36]:
class Man:
    def __init__(self, name): # Constructor
        self.name = name
        print("Initialized!")
        
    def hello(self): # Method 1
        print("Hello " + self.name + "!")
        
    def goodbye(self): # Method 2
        print("Good-bye " + self.name + "!")

In [35]:
m = Man("David")
m.hello()
m.goodbye()

Initialized!
Hello David!
Good-bye David!


# Introduction to `numpy`

## `numpy` array

In [2]:
import numpy as np

In [3]:
x = np.array([1.0, 2.0, 3.0])
print(x)
type(x)

[1. 2. 3.]


numpy.ndarray

In [4]:
y = np.array([2., 4., 6.])
x + y

array([3., 6., 9.])

In [5]:
x - y

array([-1., -2., -3.])

In [6]:
x / y

array([0.5, 0.5, 0.5])

## `numpy` broadcast

In [7]:
x = np.array([1., 2., 3.])
x / 2.

array([0.5, 1. , 1.5])

In [8]:
A = np.array([[1, 2], [3, 4]])
B = np.array([10, 20])
A * B

array([[10, 40],
       [30, 80]])

In [13]:
A = np.array([[1, 2], [3, 4]])
B = np.array([[1, 4], [6, 8]])
print(A * B) # element-wise multiplication
print(np.matmul(A, B)) # usual matrix multiplication

[[ 1  8]
 [18 32]]
[[13 20]
 [27 44]]


## Finding elements

In [18]:
X = np.array([[51, 55], [14, 19], [0, 4]])
print(X)

[[51 55]
 [14 19]
 [ 0  4]]


In [19]:
X[0]

array([51, 55])

In [20]:
X[0][1]

55

In [21]:
for row in X:
    print(row)

[51 55]
[14 19]
[0 4]


In [22]:
X > 15

array([[ True,  True],
       [False,  True],
       [False, False]])

In [23]:
X = X.flatten()
print(X)

[51 55 14 19  0  4]


In [25]:
X[X > 15]

array([51, 55, 19])

## Basic programming commands

In [27]:
for idx in range(5):
    print(idx)

0
1
2
3
4


In [29]:
for idx in range(6):
    if idx % 2 == 0:
        print(idx)

0
2
4


In [31]:
idx = 0
num = 0 
while idx < 10:
    num += idx
    idx += 1
print(num)

45


## Exercise

### 1.

Write a Python function which returns the size of matrix as below.

Input:
```python
A = np.array([[1, 1, 2], [2, 1, 1]])
print(SizeOfMatrix(A))
```

Output:
```python
[2,3]
```

(Hint: use `len` function)

### 2.

Write a Python function which takes a matrix with pivots and returns a matrix with row exchanged.

Input:
```python
A = np.array([[0, 1, 2], [0, 0, 1], [1, 2, 0]])
print(RowExchange(A))
```

Output:
```python
[[1, 2, 0], [0, 1, 2], [0, 0, 1]]
```

